//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShellBat.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShellBat.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DIR&gt;.
        /// </summary>
        internal static string _Dir_ {
            get {
                return ResourceManager.GetString("_Dir_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ShellBat.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favorites.
        /// </summary>
        internal static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string AdministratorMode {
            get {
                return ResourceManager.GetString("AdministratorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        internal static string Algorithm {
            get {
                return ResourceManager.GetString("Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        internal static string Alt {
            get {
                return ResourceManager.GetString("Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShellBat.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange instances....
        /// </summary>
        internal static string ArrangeInstances {
            get {
                return ResourceManager.GetString("ArrangeInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto play.
        /// </summary>
        internal static string AutoPlay {
            get {
                return ResourceManager.GetString("AutoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows bash.
        /// </summary>
        internal static string Bash {
            get {
                return ResourceManager.GetString("Bash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing.
        /// </summary>
        internal static string Browsing {
            get {
                return ResourceManager.GetString("Browsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        internal static string Builtin {
            get {
                return ResourceManager.GetString("Builtin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes per row.
        /// </summary>
        internal static string BytesPerRow {
            get {
                return ResourceManager.GetString("BytesPerRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All caches were cleared.
        /// </summary>
        internal static string CacheCleared {
            get {
                return ResourceManager.GetString("CacheCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot navigate to the &apos;{0}&apos; folder..
        /// </summary>
        internal static string CannotNavigate {
            get {
                return ResourceManager.GetString("CannotNavigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates....
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear caches.
        /// </summary>
        internal static string ClearCaches {
            get {
                return ResourceManager.GetString("ClearCaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close ShellBat.
        /// </summary>
        internal static string CloseApplication {
            get {
                return ResourceManager.GetString("CloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close window.
        /// </summary>
        internal static string CloseWindow {
            get {
                return ResourceManager.GetString("CloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL has been included or excluded by a default rule. Default rules are set during setup or first run..
        /// </summary>
        internal static string CLUSIONREASON_DEFAULT {
            get {
                return ResourceManager.GetString("CLUSIONREASON_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL has been included or excluded by a group policy..
        /// </summary>
        internal static string CLUSIONREASON_GROUPPOLICY {
            get {
                return ResourceManager.GetString("CLUSIONREASON_GROUPPOLICY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL has been excluded because its scope in unknown. There is no scope that would include or exclude this URL so it is excluded by default..
        /// </summary>
        internal static string CLUSIONREASON_UNKNOWNSCOPE {
            get {
                return ResourceManager.GetString("CLUSIONREASON_UNKNOWNSCOPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL has been included or excluded by a user rule. User rules are set either by the user through Indexing Options..
        /// </summary>
        internal static string CLUSIONREASON_USER {
            get {
                return ResourceManager.GetString("CLUSIONREASON_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; is not available in this context..
        /// </summary>
        internal static string CommandNotAvailableInThisContext {
            get {
                return ResourceManager.GetString("CommandNotAvailableInThisContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command prompt.
        /// </summary>
        internal static string CommandPrompt {
            get {
                return ResourceManager.GetString("CommandPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the operation?.
        /// </summary>
        internal static string ConfirmCancel {
            get {
                return ResourceManager.GetString("ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items.
        /// </summary>
        internal static string ContextMenuItems {
            get {
                return ResourceManager.GetString("ContextMenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to....
        /// </summary>
        internal static string CopyTo {
            get {
                return ResourceManager.GetString("CopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl.
        /// </summary>
        internal static string Ctrl {
            get {
                return ResourceManager.GetString("Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date modified.
        /// </summary>
        internal static string DateModified {
            get {
                return ResourceManager.GetString("DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all history.
        /// </summary>
        internal static string DeleteHistory {
            get {
                return ResourceManager.GetString("DeleteHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details options.
        /// </summary>
        internal static string DetailsOptions {
            get {
                return ResourceManager.GetString("DetailsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        internal static string Diagnostics {
            get {
                return ResourceManager.GetString("Diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Signatures.
        /// </summary>
        internal static string DigitalSignatures {
            get {
                return ResourceManager.GetString("DigitalSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display title.
        /// </summary>
        internal static string DisplayTitle {
            get {
                return ResourceManager.GetString("DisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShellBat Document.
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit address.
        /// </summary>
        internal static string EditAddress {
            get {
                return ResourceManager.GetString("EditAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eject.
        /// </summary>
        internal static string Eject {
            get {
                return ResourceManager.GetString("Eject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty recycle bin.
        /// </summary>
        internal static string EmptyRecycleBin {
            get {
                return ResourceManager.GetString("EmptyRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        internal static string Encoding {
            get {
                return ResourceManager.GetString("Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start &apos;{0}&apos; folder watcher..
        /// </summary>
        internal static string EntryWatcherError {
            get {
                return ResourceManager.GetString("EntryWatcherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was modified.
        /// </summary>
        internal static string EventChanged {
            get {
                return ResourceManager.GetString("EventChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was created.
        /// </summary>
        internal static string EventCreated {
            get {
                return ResourceManager.GetString("EventCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0} was deleted.
        /// </summary>
        internal static string EventDeleted {
            get {
                return ResourceManager.GetString("EventDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was renamed to &apos;{1}&apos;.
        /// </summary>
        internal static string EventRenamed {
            get {
                return ResourceManager.GetString("EventRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude files.
        /// </summary>
        internal static string ExcludeFiles {
            get {
                return ResourceManager.GetString("ExcludeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude folders.
        /// </summary>
        internal static string ExcludeFolders {
            get {
                return ResourceManager.GetString("ExcludeFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand (${others}).
        /// </summary>
        internal static string ExpandOthers {
            get {
                return ResourceManager.GetString("ExpandOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as CSV....
        /// </summary>
        internal static string ExportAsCsv {
            get {
                return ResourceManager.GetString("ExportAsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export extensions definitions as CSV.
        /// </summary>
        internal static string ExportExtensionsAsCsv {
            get {
                return ResourceManager.GetString("ExportExtensionsAsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract to....
        /// </summary>
        internal static string ExtractTo {
            get {
                return ResourceManager.GetString("ExtractTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill height.
        /// </summary>
        internal static string FillHeight {
            get {
                return ResourceManager.GetString("FillHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill width.
        /// </summary>
        internal static string FillWidth {
            get {
                return ResourceManager.GetString("FillWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find strings.
        /// </summary>
        internal static string FindStrings {
            get {
                return ResourceManager.GetString("FindStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search strings (ansi, unicode) in files.
        /// </summary>
        internal static string FindStringsDescription {
            get {
                return ResourceManager.GetString("FindStringsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase binary offset.
        /// </summary>
        internal static string FindStringsPosition {
            get {
                return ResourceManager.GetString("FindStringsPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        internal static string FindStringsText {
            get {
                return ResourceManager.GetString("FindStringsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder was updated by a background action because ${reason}..
        /// </summary>
        internal static string FolderUpdated {
            get {
                return ResourceManager.GetString("FolderUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path was copied to clipboard..
        /// </summary>
        internal static string FullPathCopiedToClipboard {
            get {
                return ResourceManager.GetString("FullPathCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GC completed.
        /// </summary>
        internal static string GCCompleted {
            get {
                return ResourceManager.GetString("GCCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global settings.
        /// </summary>
        internal static string GlobalSettings {
            get {
                return ResourceManager.GetString("GlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to &apos;${backFullDisplayName}&apos;.
        /// </summary>
        internal static string GoBackTo {
            get {
                return ResourceManager.GetString("GoBackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go forward.
        /// </summary>
        internal static string GoForward {
            get {
                return ResourceManager.GetString("GoForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go forward to &apos;${forwardFullDisplayName}&apos;.
        /// </summary>
        internal static string GoForwardTo {
            get {
                return ResourceManager.GetString("GoForwardTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go up.
        /// </summary>
        internal static string GoUp {
            get {
                return ResourceManager.GetString("GoUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go up to &apos;${upFullDisplayName}&apos;.
        /// </summary>
        internal static string GoUpTo {
            get {
                return ResourceManager.GetString("GoUpTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        internal static string Graphics {
            get {
                return ResourceManager.GetString("Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight CR/LF.
        /// </summary>
        internal static string HighlightCrLf {
            get {
                return ResourceManager.GetString("HighlightCrLf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History ({0} items) was deleted.
        /// </summary>
        internal static string HistoryDeleted {
            get {
                return ResourceManager.GetString("HistoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontally.
        /// </summary>
        internal static string Horizontally {
            get {
                return ResourceManager.GetString("Horizontally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontally on all screens.
        /// </summary>
        internal static string HorizontallyOnAllScreens {
            get {
                return ResourceManager.GetString("HorizontallyOnAllScreens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Metadata.
        /// </summary>
        internal static string ImageMetadata {
            get {
                return ResourceManager.GetString("ImageMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images options.
        /// </summary>
        internal static string ImagesOptions {
            get {
                return ResourceManager.GetString("ImagesOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include hidden files.
        /// </summary>
        internal static string IncludeHidden {
            get {
                return ResourceManager.GetString("IncludeHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include system files.
        /// </summary>
        internal static string IncludeSystem {
            get {
                return ResourceManager.GetString("IncludeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance.
        /// </summary>
        internal static string Instance {
            get {
                return ResourceManager.GetString("Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instances.
        /// </summary>
        internal static string Instances {
            get {
                return ResourceManager.GetString("Instances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance settings.
        /// </summary>
        internal static string InstanceSettings {
            get {
                return ResourceManager.GetString("InstanceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instancing.
        /// </summary>
        internal static string Instancing {
            get {
                return ResourceManager.GetString("Instancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key combination &apos;{0}&apos; is invalid or already used..
        /// </summary>
        internal static string InvalidShortcutKey {
            get {
                return ResourceManager.GetString("InvalidShortcutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer.
        /// </summary>
        internal static string Issuer {
            get {
                return ResourceManager.GetString("Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard shortcuts.
        /// </summary>
        internal static string KeyboardShortcuts {
            get {
                return ResourceManager.GetString("KeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link properties.
        /// </summary>
        internal static string LinkProperties {
            get {
                return ResourceManager.GetString("LinkProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load theme....
        /// </summary>
        internal static string LoadTheme {
            get {
                return ResourceManager.GetString("LoadTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowercase.
        /// </summary>
        internal static string Lowercase {
            get {
                return ResourceManager.GetString("Lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize or Restore.
        /// </summary>
        internal static string Maximize_Restore {
            get {
                return ResourceManager.GetString("Maximize_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize window.
        /// </summary>
        internal static string MaximizeWindow {
            get {
                return ResourceManager.GetString("MaximizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimap.
        /// </summary>
        internal static string Minimap {
            get {
                return ResourceManager.GetString("Minimap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        internal static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize window.
        /// </summary>
        internal static string MinimizeWindow {
            get {
                return ResourceManager.GetString("MinimizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount.
        /// </summary>
        internal static string Mount {
            get {
                return ResourceManager.GetString("Mount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount in new instance.
        /// </summary>
        internal static string MountInNewInstance {
            get {
                return ResourceManager.GetString("MountInNewInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount in new instance in &apos;{0}&apos;.
        /// </summary>
        internal static string MountInNewInstanceScreen {
            get {
                return ResourceManager.GetString("MountInNewInstanceScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to....
        /// </summary>
        internal static string MoveTo {
            get {
                return ResourceManager.GetString("MoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance &apos;${name}&apos; settings.
        /// </summary>
        internal static string NamedInstanceSettings {
            get {
                return ResourceManager.GetString("NamedInstanceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to needs restart.
        /// </summary>
        internal static string NeedsRestart {
            get {
                return ResourceManager.GetString("NeedsRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        internal static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        internal static string NewFolderName {
            get {
                return ResourceManager.GetString("NewFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New terminal.
        /// </summary>
        internal static string NewTerminal {
            get {
                return ResourceManager.GetString("NewTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none detected).
        /// </summary>
        internal static string NoneDetected {
            get {
                return ResourceManager.GetString("NoneDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no updates available..
        /// </summary>
        internal static string NoUpdates {
            get {
                return ResourceManager.GetString("NoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open as folder.
        /// </summary>
        internal static string OpenAsFolder {
            get {
                return ResourceManager.GetString("OpenAsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open configuration folder.
        /// </summary>
        internal static string OpenConfig {
            get {
                return ResourceManager.GetString("OpenConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &apos;Desktop&apos;.
        /// </summary>
        internal static string OpenDesktop {
            get {
                return ResourceManager.GetString("OpenDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open favorites.
        /// </summary>
        internal static string OpenFavorites {
            get {
                return ResourceManager.GetString("OpenFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open from Explorer....
        /// </summary>
        internal static string OpenFromExplorer {
            get {
                return ResourceManager.GetString("OpenFromExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open from Visual Studio....
        /// </summary>
        internal static string OpenFromVisualStudio {
            get {
                return ResourceManager.GetString("OpenFromVisualStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open history.
        /// </summary>
        internal static string OpenHistory {
            get {
                return ResourceManager.GetString("OpenHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new instance.
        /// </summary>
        internal static string OpenInNewInstance {
            get {
                return ResourceManager.GetString("OpenInNewInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new instance as administrator.
        /// </summary>
        internal static string OpenInNewInstanceAdministrator {
            get {
                return ResourceManager.GetString("OpenInNewInstanceAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new instance in &apos;{0}&apos;.
        /// </summary>
        internal static string OpenInNewInstanceScreen {
            get {
                return ResourceManager.GetString("OpenInNewInstanceScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open instance settings.
        /// </summary>
        internal static string OpenInstanceSettings {
            get {
                return ResourceManager.GetString("OpenInstanceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open keyboard shortcuts.
        /// </summary>
        internal static string OpenKeyboardShortcuts {
            get {
                return ResourceManager.GetString("OpenKeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open logs folder.
        /// </summary>
        internal static string OpenLogsFolder {
            get {
                return ResourceManager.GetString("OpenLogsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a new instance.
        /// </summary>
        internal static string OpenNewInstance {
            get {
                return ResourceManager.GetString("OpenNewInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a new instance as administrator.
        /// </summary>
        internal static string OpenNewInstanceAdministrator {
            get {
                return ResourceManager.GetString("OpenNewInstanceAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open new instance on other screen.
        /// </summary>
        internal static string OpenNewInstanceOnOtherScreen {
            get {
                return ResourceManager.GetString("OpenNewInstanceOnOtherScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a new instance in &apos;{0}&apos;.
        /// </summary>
        internal static string OpenNewInstanceScreen {
            get {
                return ResourceManager.GetString("OpenNewInstanceScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &apos;Recycle Bin&apos;.
        /// </summary>
        internal static string OpenRecycleBin {
            get {
                return ResourceManager.GetString("OpenRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        internal static string OpenSettings {
            get {
                return ResourceManager.GetString("OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open target folder.
        /// </summary>
        internal static string OpenTargetFolder {
            get {
                return ResourceManager.GetString("OpenTargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open terminal.
        /// </summary>
        internal static string OpenTerminal {
            get {
                return ResourceManager.GetString("OpenTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &apos;This PC&apos;.
        /// </summary>
        internal static string OpenThisPC {
            get {
                return ResourceManager.GetString("OpenThisPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open viewers.
        /// </summary>
        internal static string OpenViewers {
            get {
                return ResourceManager.GetString("OpenViewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with....
        /// </summary>
        internal static string OpenWith {
            get {
                return ResourceManager.GetString("OpenWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with Explorer.
        /// </summary>
        internal static string OpenWithExplorer {
            get {
                return ResourceManager.GetString("OpenWithExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with new ShellBat terminal....
        /// </summary>
        internal static string OpenWithNewTerminal {
            get {
                return ResourceManager.GetString("OpenWithNewTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OpenWithShell {
            get {
                return ResourceManager.GetString("OpenWithShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with ShellBat.
        /// </summary>
        internal static string OpenWithShellBat {
            get {
                return ResourceManager.GetString("OpenWithShellBat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with ShellBat terminal....
        /// </summary>
        internal static string OpenWithTerminal {
            get {
                return ResourceManager.GetString("OpenWithTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        internal static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is password protected.
        /// </summary>
        internal static string PasswordProtected {
            get {
                return ResourceManager.GetString("PasswordProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste shortcut.
        /// </summary>
        internal static string PasteShortcut {
            get {
                return ResourceManager.GetString("PasteShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin &apos;{0}&apos; viewer.
        /// </summary>
        internal static string PinViewer {
            get {
                return ResourceManager.GetString("PinViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powershell.
        /// </summary>
        internal static string Powershell {
            get {
                return ResourceManager.GetString("Powershell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string PreviewHandler {
            get {
                return ResourceManager.GetString("PreviewHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        internal static string PrevPage {
            get {
                return ResourceManager.GetString("PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process &apos;{0}&apos; has exited..
        /// </summary>
        internal static string ProcessExited {
            get {
                return ResourceManager.GetString("ProcessExited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit all instances.
        /// </summary>
        internal static string QuitAllInstances {
            get {
                return ResourceManager.GetString("QuitAllInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit....
        /// </summary>
        internal static string QuitInstance {
            get {
                return ResourceManager.GetString("QuitInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive.
        /// </summary>
        internal static string Recursive {
            get {
                return ResourceManager.GetString("Recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search folders recursively.
        /// </summary>
        internal static string RecursiveSearch {
            get {
                return ResourceManager.GetString("RecursiveSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle.
        /// </summary>
        internal static string Recycle {
            get {
                return ResourceManager.GetString("Recycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle bin.
        /// </summary>
        internal static string RecycleBin {
            get {
                return ResourceManager.GetString("RecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh current theme.
        /// </summary>
        internal static string RefreshCurrentTheme {
            get {
                return ResourceManager.GetString("RefreshCurrentTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register shell integration.
        /// </summary>
        internal static string RegisterShellIntegrations {
            get {
                return ResourceManager.GetString("RegisterShellIntegrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unreachable items from favorites.
        /// </summary>
        internal static string RemoveDeletedItemsFromFavorites {
            get {
                return ResourceManager.GetString("RemoveDeletedItemsFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unreachable items from history.
        /// </summary>
        internal static string RemoveDeletedItemsFromHistory {
            get {
                return ResourceManager.GetString("RemoveDeletedItemsFromHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from favorites.
        /// </summary>
        internal static string RemoveFromFavorites {
            get {
                return ResourceManager.GetString("RemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render PDF thumbnails.
        /// </summary>
        internal static string RenderPdfThumbnails {
            get {
                return ResourceManager.GetString("RenderPdfThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart as administrator....
        /// </summary>
        internal static string RestartAsAdministrator {
            get {
                return ResourceManager.GetString("RestartAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore all recycle bin items.
        /// </summary>
        internal static string RestoreAllRecycleBinItems {
            get {
                return ResourceManager.GetString("RestoreAllRecycleBinItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run action.
        /// </summary>
        internal static string RunAction {
            get {
                return ResourceManager.GetString("RunAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all pages....
        /// </summary>
        internal static string SaveAllPages {
            get {
                return ResourceManager.GetString("SaveAllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose target folder (format is &apos;{0}&apos;).
        /// </summary>
        internal static string SaveAllPagesChooseFolder {
            get {
                return ResourceManager.GetString("SaveAllPagesChooseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save instance configuration....
        /// </summary>
        internal static string SaveInstance {
            get {
                return ResourceManager.GetString("SaveInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save page....
        /// </summary>
        internal static string SavePage {
            get {
                return ResourceManager.GetString("SavePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current theme....
        /// </summary>
        internal static string SaveTheme {
            get {
                return ResourceManager.GetString("SaveTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving page {0} / {1} ....
        /// </summary>
        internal static string SavingPage {
            get {
                return ResourceManager.GetString("SavingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path.
        /// </summary>
        internal static string SearchFilePath {
            get {
                return ResourceManager.GetString("SearchFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string SearchIndex {
            get {
                return ResourceManager.GetString("SearchIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched {0} files....
        /// </summary>
        internal static string SearchingCount {
            get {
                return ResourceManager.GetString("SearchingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search options.
        /// </summary>
        internal static string SearchOptions {
            get {
                return ResourceManager.GetString("SearchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search terms....
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative path.
        /// </summary>
        internal static string SearchRelativePath {
            get {
                return ResourceManager.GetString("SearchRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found ${count} matches.
        /// </summary>
        internal static string SearchResultsFound {
            get {
                return ResourceManager.GetString("SearchResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection options.
        /// </summary>
        internal static string SelectionOptions {
            get {
                return ResourceManager.GetString("SelectionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send anonymous error report to the developer?.
        /// </summary>
        internal static string SendErrorReport {
            get {
                return ResourceManager.GetString("SendErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows context menu....
        /// </summary>
        internal static string ShellContextMenu {
            get {
                return ResourceManager.GetString("ShellContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell integration registered.
        /// </summary>
        internal static string ShellIntegrationsRegistered {
            get {
                return ResourceManager.GetString("ShellIntegrationsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell integration unregistered.
        /// </summary>
        internal static string ShellIntegrationsUnregistered {
            get {
                return ResourceManager.GetString("ShellIntegrationsUnregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show compressed as file.
        /// </summary>
        internal static string ShowCompressedAsFile {
            get {
                return ResourceManager.GetString("ShowCompressedAsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show icons.
        /// </summary>
        internal static string ShowIcons {
            get {
                return ResourceManager.GetString("ShowIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show image files only.
        /// </summary>
        internal static string ShowImagesOnly {
            get {
                return ResourceManager.GetString("ShowImagesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show thumbnails.
        /// </summary>
        internal static string ShowThumbnails {
            get {
                return ResourceManager.GetString("ShowThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signer.
        /// </summary>
        internal static string Signer {
            get {
                return ResourceManager.GetString("Signer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        internal static string Software {
            get {
                return ResourceManager.GetString("Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        internal static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square thumbnails.
        /// </summary>
        internal static string SquareThumbnails {
            get {
                return ResourceManager.GetString("SquareThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to instance....
        /// </summary>
        internal static string SwitchToInstance {
            get {
                return ResourceManager.GetString("SwitchToInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync ShellBat.
        /// </summary>
        internal static string SyncShellBat {
            get {
                return ResourceManager.GetString("SyncShellBat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize ShellBat window from Terminal window.
        /// </summary>
        internal static string SyncShellBatTooltip {
            get {
                return ResourceManager.GetString("SyncShellBatTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Terminal.
        /// </summary>
        internal static string SyncTerminal {
            get {
                return ResourceManager.GetString("SyncTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize Terminal window from ShellBat window.
        /// </summary>
        internal static string SyncTerminalTooltip {
            get {
                return ResourceManager.GetString("SyncTerminalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System info.
        /// </summary>
        internal static string SysInfo {
            get {
                return ResourceManager.GetString("SysInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminals.
        /// </summary>
        internal static string Terminals {
            get {
                return ResourceManager.GetString("Terminals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files only.
        /// </summary>
        internal static string TextFilesOnly {
            get {
                return ResourceManager.GetString("TextFilesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search only in files perceived as containing only text.
        /// </summary>
        internal static string TextFilesOnlyDescription {
            get {
                return ResourceManager.GetString("TextFilesOnlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        internal static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This.
        /// </summary>
        internal static string ThisInstance {
            get {
                return ResourceManager.GetString("ThisInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnails size.
        /// </summary>
        internal static string ThumbnailsSize {
            get {
                return ResourceManager.GetString("ThumbnailsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiled.
        /// </summary>
        internal static string Tiled {
            get {
                return ResourceManager.GetString("Tiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles on all screens.
        /// </summary>
        internal static string TiledOnAllScreens {
            get {
                return ResourceManager.GetString("TiledOnAllScreens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock (Mark Of The Web).
        /// </summary>
        internal static string Unblock {
            get {
                return ResourceManager.GetString("Unblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin &apos;{0}&apos; viewer.
        /// </summary>
        internal static string UnpinViewer {
            get {
                return ResourceManager.GetString("UnpinViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister shell integration.
        /// </summary>
        internal static string UnregisterShellIntegrations {
            get {
                return ResourceManager.GetString("UnregisterShellIntegrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        internal static string UnspecifiedInstanceName {
            get {
                return ResourceManager.GetString("UnspecifiedInstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of Windows ({0}) is unsupported..
        /// </summary>
        internal static string UnsupportedWindowsVersion {
            get {
                return ResourceManager.GetString("UnsupportedWindowsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version &apos;{0}&apos; is available, do you want to quit all instances and upgrade?.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShellBat was updated successfully to version &apos;{0}&apos;.
        /// </summary>
        internal static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed..
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update is not supported in development mode.
        /// </summary>
        internal static string UpdateIsNotSupported {
            get {
                return ResourceManager.GetString("UpdateIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShellBat Update.
        /// </summary>
        internal static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating ....
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertically.
        /// </summary>
        internal static string Vertically {
            get {
                return ResourceManager.GetString("Vertically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertically on all screens.
        /// </summary>
        internal static string VerticallyOnAllScreens {
            get {
                return ResourceManager.GetString("VerticallyOnAllScreens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View....
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewers.
        /// </summary>
        internal static string Viewers {
            get {
                return ResourceManager.GetString("Viewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View filter.
        /// </summary>
        internal static string ViewFilter {
            get {
                return ResourceManager.GetString("ViewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in....
        /// </summary>
        internal static string ViewIn {
            get {
                return ResourceManager.GetString("ViewIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application requires the WebView2 runtime to be installed. Please install it from the Microsoft website at &lt;A HREF=&quot;{0}&quot;&gt;{0}&lt;/A&gt; and restart this application..
        /// </summary>
        internal static string WebView2Link {
            get {
                return ResourceManager.GetString("WebView2Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView2 Runtime Not Found.
        /// </summary>
        internal static string WebView2NotFound {
            get {
                return ResourceManager.GetString("WebView2NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowing.
        /// </summary>
        internal static string Windowing {
            get {
                return ResourceManager.GetString("Windowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Powershell.
        /// </summary>
        internal static string WindowsPowershell {
            get {
                return ResourceManager.GetString("WindowsPowershell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows search.
        /// </summary>
        internal static string WindowsSearch {
            get {
                return ResourceManager.GetString("WindowsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in files using Windows Search (AQS).
        /// </summary>
        internal static string WindowsSearchDescription {
            get {
                return ResourceManager.GetString("WindowsSearchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows Search service is not configured to index the current folder &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string WindowsSearchExcluded {
            get {
                return ResourceManager.GetString("WindowsSearchExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap.
        /// </summary>
        internal static string Wrap {
            get {
                return ResourceManager.GetString("Wrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string WrapCharacter {
            get {
                return ResourceManager.GetString("WrapCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string WrapNone {
            get {
                return ResourceManager.GetString("WrapNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        internal static string WrapWord {
            get {
                return ResourceManager.GetString("WrapWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word break.
        /// </summary>
        internal static string WrapWordBreak {
            get {
                return ResourceManager.GetString("WrapWordBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        internal static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
