namespace ShellBat.Model;

public enum WebEventType
{
    Unspecified = 0,
    CaptionSizeChanged = 1,
    WindowNotOpen = 2,
    VisualViewportChanged = 3,
    Close = 4,
    Minimize = 5,
    MaximizeRestore = 6,
    Navigate = 7,
    ConsoleLog = 8,
    OnSearchDoubleClicked = 9,
    RemoveDeletedItemsFromFavorites = 10,
    KeyDown = 11,
    KeyUp = 12,
    MoveHistoryBack = 13,
    MoveHistoryForward = 14,
    Log = 15,
    CaptionButtonsSizeChanged = 16,
    OpenNewInstanceAdministrator = 17,
    EntryDoubleClicked = 18,
    UpdateNow = 19,
    ArrangeInstances = 20,
    SetGlobalEvents = 21,
    OpenLogsFolder = 22,
    RemoveDeletedItemsFromHistory = 23,
    ExportAsCsv = 24,
    ExportExtensionsAsCsv = 25,
    DisposeChildWindows = 26,
    OpenNewInstanceOnScreen = 27,
    TerminalKeyEvent = 28,
    ReadyStateChange = 29,
    OpenNewInstance = 30,
    QuitAllInstances = 31,
    SwitchToInstance = 32,
    QuitInstance = 33,
}
